steps:
  # Build the Docker image from the backend directory
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      './backend'
    ]
    id: Build

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    ]
    id: Push

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--region', '$_DEPLOY_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port=8080',
      '--set-env-vars', 'NODE_ENV=production,PORT=8080,API_VERSION=v1',
      '--memory', '512Mi',
      '--cpu', '1',
      '--concurrency', '80',
      '--timeout', '300'
    ]
    id: Deploy

# Configure substitution variables
substitutions:
  _GCR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: aegis
  _DEPLOY_REGION: us-central1

options:
  substitution_option: ALLOW_LOOSE