# Google App Engine configuration for Last Aegis Backend
runtime: nodejs18

env_variables:
  NODE_ENV: production
  PORT: 8080
  API_VERSION: v1
  DATABASE_URL: postgresql://postgres:TMy<R)h}sLr3hKl@34.139.105.181:5432/postgres
  CLOUD_SQL_INSTANCE_CONNECTION_NAME: seraphic-fire-471503-e6:us-central1:last-aegis-db
  JWT_SECRET: your-super-secure-jwt-secret-key-for-production-min-256-bits-long-change-this
  BCRYPT_ROUNDS: 12
  RATE_LIMIT_WINDOW: 15
  RATE_LIMIT_MAX: 100
  RATE_LIMIT_AUTH_MAX: 5
  CLIENT_URL: https://lastaegis.app
  LOG_LEVEL: info

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

beta_settings:
  cloud_sql_instances: seraphic-fire-471503-e6:us-central1:last-aegis-db